//
//  FunctionCall.swift
//  
//
//  Created by Ronald Mannak on 3/27/24.
//

import Foundation

/// Deprecated and replaced by `tool_calls`. The name and arguments of a function that should be called, as generated by the model
/// # See also
/// [OpenAI API Reference](https://platform.openai.com/docs/api-reference/chat/object)
@available(*, deprecated, message: "Use tools and ToolChoice instead")
public struct FunctionCall: Codable {
    
    /// The arguments to call the function with, as generated by the model in JSON format. Note that the model does not always generate valid JSON, and may hallucinate parameters not defined by your function schema. Validate the arguments in your code before calling your function.
    let arguments: String
    
    /// The name of the function to call.
    let name: String
}
