//
//  File.swift
//  
//
//  Created by Ronald Mannak on 3/26/24.
//

import Foundation

/// The tool calls generated by the model, such as function calls.
/// # See also
/// [OpenAI API Reference](https://platform.openai.com/docs/api-reference/chat/object)
struct ToolCall: Codable {
    
    enum ToolCallType: Codable {
        case function
    }
        
    /// The ID of the tool call
    /// # See also
    /// [OpenAI API Reference](https://platform.openai.com/docs/api-reference/chat/create)
    let id: String
    
    /// The type of the tool. Currently, only `function` is supported.
    /// # See also
    /// [OpenAI API Reference](https://platform.openai.com/docs/api-reference/chat/create)
    let type: ToolCallType
    
    /// The function that the model called.
    /// # See also
    /// [OpenAI API Reference](https://platform.openai.com/docs/api-reference/chat/create)
    let function: FunctionToolCall
}

struct FunctionToolCall: Codable {
    
    /// The name of the function to call.
    let name: String
    
    /// The arguments to call the function with, as generated by the model in JSON format. Note that the model does not always generate valid JSON, and may hallucinate parameters not defined by your function schema. Validate the arguments in your code before calling your function.
    let arguments: String
}
